POST http://localhost:5001/api/products/seed/
Content-Type: application/json

{
    "name":"JNX Sports The Ripper",
    "image":"https://cdn.muscleandstrength.com/store/media/catalog/product/cache/all/image/700x700/602f0fa2c1f0d1ba5e241f914e856ff9/t/h/the-ripper-blood-orange-30-serve_2.jpg",
    "brand":"JNX Sports",
    "description":"The Ultimate Fast Acting, Full Strength Fat Burner!*",
    "features":["Fast acting formula*","Full strength fat-burner*","Supports appetite control*","9 intense great tasting flavors"],
    "rating":94,
    "numReviews":731,
    "category":"Fat Burner",
    "ingredient":"Citric Acid, Malic Acid, Calcium Silicate, Silicon Dioxide, Natural and Artificial Flavors, Beet Juice (color), Sucralose, Acesulfame Potassium",
    "directions":"Begin drinking (1) serving (1 scoop) mixed with 6-8 ounces (180-250mls) of cold water on an empty stomach 15-30 minutes before breakfast for the first two (2) days to assess tolerance. an additional 1 scoop may be taken 5-6 hours later or as directed by a qualified healthcare practitioner. For best results, use for 60 days in combination with diet and exercise. Do not exceed 2 servings in a 24 hour period.",
    "warning":"Always assess your tolerance with a single scoop. This product is only intended to be consumed by healthy adults 18 years of age or older. Not for use by those with pre-existing medical conditions or those taking any medications, young children under the age of 18, pregnant or lactating women, or individuals sensitive to caffeine or beta alanine. Discontinue use and consult your health care professional if you experience any adverse reaction to this product. Do not consume with caffeine, alcohol, or stimulants from other sources. To avoid sleeplessness do not consume within 4 hours of bedtime. You may experience harmless short term skin tingles. Store in a cool, dry place. KEEP OUT OF REACH OF CHILDREN.",
    "extraInfo":
}

####

GET http://localhost:5000/api/products/610cfe2cf4aa8733f47c2f62

#####

GET  http://localhost:5000/api/review/getAll/603cd94f39e7893b1cb3e4ed/1


#####

PUT http://localhost:5001/api/review/update
Content-Type: application/json

{
    "review":{
        "content":"Always assess your tolerance with a single scoop. This product is only intended to be consumed by healthy adults 18 years of age or older. Not for use by those with pre-existing medical conditions or those taking any medications, young children under the age of 18, pregnant or lactating women, or individuals sensitive to caffeine or beta alanine. Discontinue use and consult your health care professional if you experience any adverse reaction to this product. Do not consume with caffeine, alcohol, or stimulants from other sources. To avoid sleeplessness do not consume within 4 hours of bedtime. You may experience harmless short term skin tingles. Store in a cool, dry place. KEEP OUT OF REACH OF CHILDREN.",
        "_id":"604b733f1ffe9b039cfbb3dc"
    }  
}

###

DELETE  http://localhost:5000/api/review/delete
Content-Type: application/json

{
    
    "_id":"605080b1bf0ab73d74020dd7",
    "userId":"5fef1d35db624d3258c938c7"
}

###
POST  http://localhost:5000/api/review/report
Content-Type: application/json

{
    "report":{
        "reviewId":"604b733f1ffe9b039cfbb3da",
        "userId":"5fef1d35db624d3258c938c7",
        "productId":"603cd94f39e7893b1cb3e4ed",
        "userName":"nur",
        "content":"Always assess your tolerance with a single scoop. This product is only intended to be consumed by healthy adults 18 years of age or older. Not for use by those with pre-existing medical conditions or those taking any medications, young children under the age of 18, pregnant or lactating women, or individuals sensitive to caffeine or beta alanine. Discontinue use and consult your health care professional if you experience any adverse reaction to this product. Do not consume with caffeine, alcohol, or stimulants from other sources. To avoid sleeplessness do not consume within 4 hours of bedtime. You may experience harmless short term skin tingles. Store in a cool, dry place. KEEP OUT OF REACH OF CHILDREN."
    }  
}

###

GET http://localhost:5000/api/review/numReviews/603cd94f39e7893b1cb3e4ed


###

GET https://cdn.muscleandstrength.com/store/skin/frontend/mnsv4/default/images/stars-svg-overlay.svg


###

GET http://localhost:5000/api/image/stars-svg-overlay.svg

### 
PUT http://localhost:5000/api/users/update
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmVmMWQzNWRiNjI0ZDMyNThjOTM4YzciLCJmaXJzdE5hbWUiOiJudXIiLCJsYXN0TmFtZSI6Im1kIiwiZW1haWwiOiJudXJAeWFob28uY29tIiwiZ2VuZGVyIjoiIiwiZ29hbCI6IiIsInRyYWluaW5nRXhwZXJpZW5jZSI6IiIsImlzQWRtaW4iOmZhbHNlLCJyZWZlcnJhbENvZGUiOiIiLCJpYXQiOjE2MTcxNzA5ODIsImV4cCI6MTYxOTc2Mjk4Mn0.5qQC0x1NMDWlkU3UGpiBq2K8mlM6Ipysuigfv8V492c

{
    "_id":"5fef1d35db624d3258c938c7",
    "something":"working!",
    "update":{"reviewingAs":"mdNur"}
}

### 
PUT http://localhost:5000/api/users/update
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmVmMWQzNWRiNjI0ZDMyNThjOTM4YzciLCJmaXJzdE5hbWUiOiJudXIiLCJsYXN0TmFtZSI6Im1kIiwiZW1haWwiOiJudXJAeWFob28uY29tIiwiZ2VuZGVyIjoiIiwiZ29hbCI6IiIsInRyYWluaW5nRXhwZXJpZW5jZSI6IiIsImlzQWRtaW4iOmZhbHNlLCJyZWZlcnJhbENvZGUiOiIiLCJpYXQiOjE2MTcxOTQ0MTEsImV4cCI6MTYxOTc4NjQxMX0.lfbtBWBBeu-OjCgzQHUHmszVstxPEnNQlllwJTU2Sp0

{
    "_id":"5fef1d35db624d3258c938c7",
    "something":"working!",
    "update":{ "$addToSet": { "evaluateHelpfulness": ["604b733f1ffe9b039cfbb3da"] } }
}


### 
PUT http://localhost:5000/api/users/update
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmVmMWQzNWRiNjI0ZDMyNThjOTM4YzciLCJmaXJzdE5hbWUiOiJudXIiLCJsYXN0TmFtZSI6Im1kIiwiZW1haWwiOiJudXJAeWFob28uY29tIiwiZ2VuZGVyIjoiIiwiZ29hbCI6IiIsInRyYWluaW5nRXhwZXJpZW5jZSI6IiIsImlzQWRtaW4iOmZhbHNlLCJyZWZlcnJhbENvZGUiOiIiLCJpYXQiOjE2MTcxOTQ0MTEsImV4cCI6MTYxOTc4NjQxMX0.lfbtBWBBeu-OjCgzQHUHmszVstxPEnNQlllwJTU2Sp0

{
    "_id":"5fef1d35db624d3258c938c7",
    "something":"working!",
    "update":{ "$set": { "evaluateHelpfulness": [] } }
}


### 
PUT http://localhost:5000/api/users/update
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmVmMWQzNWRiNjI0ZDMyNThjOTM4YzciLCJmaXJzdE5hbWUiOiJudXIiLCJsYXN0TmFtZSI6Im1kIiwiZW1haWwiOiJudXJAeWFob28uY29tIiwiZ2VuZGVyIjoiIiwiZ29hbCI6IiIsInRyYWluaW5nRXhwZXJpZW5jZSI6IiIsImlzQWRtaW4iOmZhbHNlLCJyZWZlcnJhbENvZGUiOiIiLCJpYXQiOjE2MTcxOTQ0MTEsImV4cCI6MTYxOTc4NjQxMX0.lfbtBWBBeu-OjCgzQHUHmszVstxPEnNQlllwJTU2Sp0

{
    "_id":"5fef1d35db624d3258c938c7",
    "something":"working!",
    "update":{ "$addToSet": { "evaluateHelpfulness": [{"reviewId":"604b733f1ffe9b039cfbb3da", "isHelpful":true}] } }
}

###
POST  http://localhost:5000/api/review/helpfulness
Content-Type: application/json

{
    "helpfulness":{
        "reviewId":"604b733f1ffe9b039cfbb3de",
        "userId":"5fef1d35db624d3258c938c7",
        "productId":"603cd94f39e7893b1cb3e4ed",
       "isHelpful":false
    }  
}

###
GET http://localhost:5000/api/review/helpfulness/5fef1d35db624d3258c938c7/603cd94f39e7893b1cb3e4ed

###

DELETE   http://localhost:5000/api/review/helpfulness/60898e58da037f11d834b77a

###

GET  http://localhost:5000/api/products/search/JNX/18


###

GET http://localhost:5000/api/products/search/numOfProducts/JNs

###

POST http://localhost:5000/api/store/cart/
Content-Type: application/json

{
  "productId":"603cd94f39e7893b1cb3e4ed",
  "userId":"5fef1d35db624d3258c938c7", 
  "quantity":"4",
  "productType":"30 Servings Blood Orange"
}

###

GEt http://localhost:5000/api/store/cart/5fef1d35db624d3258c938c7

###

PUT http://localhost:5000/api/store/cart/quantity
Content-Type: application/json

{
  "cartItemId":"60fe4fcaf2135b32b8c8c7c3",
  "qty":"30"
}


### 


DELETE  http://localhost:5000/api/store/cart
Content-Type: application/json

{
  "cartItemId":"60fe4fcaf2135b32b8c8c7c3"
 
}

###

POST http://localhost:5000/api/store/brand
Content-Type: application/json

{
  "name":"MuscleTech",
  "image":"/images/MT_logo_2020_black_400.jpg",
  "title":"PUSHING THE LIMITS OF SCIENCE AND HUMAN POTENTIAL",
  "description":"MuscleTech® was born out of an obsession to redefine the limits of science and human potential. With our commitment to research, development and innovation, we’ve been globally recognized as one of the leading sports nutrition brands in the industry and continue to be one of America’s elite names for redefining performance through cutting-edge products and high-quality ingredients. Backed by America’s #1 selling sports supplement company, and with distribution in over 140 countries, MuscleTech® has emerged as one of the most recognized sports nutrition brands worldwide.",
  "video":"https://i.vimeocdn.com/video/960042876?mw=700&mh=394"

}

###

POST http://localhost:5000/api/products/deal
Content-Type: application/json

{
    "description":"Buy 1 MuscleTech Hydroxycut Hardcore Next Gen Yohimbe Free for only €17.54! Limited time only.",
    "type":"LIMITED TIME PRICE CUT",
    "belongTo":"60a7f6464faa5a0320ddf5aa",
    "expiredAt":"2021-08-23T15:03:20.972+00:00"

}

###

PUT http://localhost:5000/api/products
Content-Type: application/json

{
    "productId":"60a54b9f49019d37d4afa7de",
    "deal":"611398cea9e6024e8094d4e3"
}

###

GET http://localhost:5000/api/products/productsWithDeal

###

GET http://localhost:5000/api/products/thisWeekDeal


