export const CART_ADD_REQUEST = "CART_ADD_REQUEST";
export const CART_ADD_SUCCESS = "CART_ADD_SUCCESS";
export const CART_ADD_FAIL = "CART_ADD_FAIL";

export const CART_GET_REQUEST = "CART_GET_REQUEST";
export const CART_GET_SUCCESS = "CART_GET_SUCCESS";
export const CART_GET_FAIL = "CART_GET_FAIL";

export const CART_ITEM_UPDATE_QTY_REQUEST = "CART_ITEM_UPDATE_QTY_REQUEST";
export const CART_ITEM_UPDATE_QTY_SUCCESS = "CART_ITEM_UPDATE_QTY_SUCCESS";
export const CART_ITEM_UPDATE_QTY_FAIL = "CART_ITEM_UPDATE_QTY_FAIL";

export const CART_ITEM_DELETE_REQUEST = "CART_ITEM_DELETE_REQUEST";
export const CART_ITEM_DELETE_SUCCESS = "CART_ITEM_DELETE_SUCCESS";
export const CART_ITEM_DELETE_FAIL = "CART_ITEM_DELETE_FAIL";
