export const PRODUCT_TOP_DEALS_REQUEST = "PRODUCT_TOP_DEALS_REQUEST";
export const PRODUCT_TOP_DEALS_SUCCESS = "PRODUCT_TOP_DEALS_SUCCESS";
export const PRODUCT_TOP_DEALS_FAIL = "PRODUCT_TOP_DEALS_FAIL";

export const PRODUCT_GET_ONE_REQUEST = "PRODUCT_GET_ONE_REQUEST";
export const PRODUCT_GET_ONE_SUCCESS = "PRODUCT_GET_ONE_SUCCESS";
export const PRODUCT_GET_ONE_FAIL = "PRODUCT_GET_ONE_FAIL";

export const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST";
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";
export const PRODUCT_ADD_FAIL = "PRODUCT_ADD_FAIL";
