export const PRODUCT_TOP_DEALS_REQUEST =
  "PRODUCT_TOP_DEALS_REQUEST";
export const PRODUCT_TOP_DEALS_SUCCESS =
  "PRODUCT_TOP_DEALS_SUCCESS";
export const PRODUCT_TOP_DEALS_FAIL = "PRODUCT_TOP_DEALS_FAIL";

export const PRODUCT_GET_ONE_REQUEST = "PRODUCT_GET_ONE_REQUEST";
export const PRODUCT_GET_ONE_SUCCESS = "PRODUCT_GET_ONE_SUCCESS";
export const PRODUCT_GET_ONE_FAIL = "PRODUCT_GET_ONE_FAIL";

export const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST";
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";
export const PRODUCT_ADD_FAIL = "PRODUCT_ADD_FAIL";

export const PRODUCT_SEARCH_REQUEST = "PRODUCT_SEARCH_REQUEST";
export const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCCESS";
export const PRODUCT_SEARCH_FAIL = "PRODUCT_SEARCH_FAIL";

export const PRODUCT_SEARCH_GET_NUM_SUCCESS =
  "PRODUCT_SEARCH_GET_NUM_SUCCESS";
export const PRODUCT_SEARCH_GET_NUM_FAIL =
  "PRODUCT_SEARCH_GET_NUM_FAIL";

export const PRODUCT_GET_WITH_DEAL_REQUEST =
  "PRODUCT_GET_WITH_DEAL_REQUEST";
export const PRODUCT_GET_WITH_DEAL_SUCCESS =
  "PRODUCT_GET_WITH_DEAL_SUCCESS";
export const PRODUCT_GET_WITH_DEAL_FAIL =
  "PRODUCT_GET_WITH_DEAL_FAIL";

export const PRODUCT_GET_THIS_WEEK_DEAL_REQUEST =
  "PRODUCT_GET_THIS_WEEK_DEAL_REQUEST";
export const PRODUCT_GET_THIS_WEEK_DEAL_SUCCESS =
  "PRODUCT_GET_THIS_WEEK_DEAL_SUCCESS";
export const PRODUCT_GET_THIS_WEEK_DEAL_FAIL =
  "PRODUCT_GET_THIS_WEEK_DEAL_FAIL";

export const PRODUCT_GET_HAS_BEEN_RATED_REQUEST =
  "PRODUCT_GET_HAS_BEEN_RATED_REQUEST";
export const PRODUCT_GET_HAS_BEEN_RATED_SUCCESS =
  "PRODUCT_GET_HAS_BEEN_RATED_SUCCESS";
export const PRODUCT_GET_HAS_BEEN_RATED_FAIL =
  "PRODUCT_GET_HAS_BEEN_RATED_FAIL";
