export const REVIEW_ADD_REVIEWS_REQUEST = "REVIEW_ADD_REVIEWS_REQUEST";
export const REVIEW_ADD_REVIEWS_SUCCESS = "REVIEW_ADD_REVIEWS_SUCCESS";
export const REVIEW_ADD_REVIEWS_FAIL = "REVIEW_ADD_REVIEWS_FAIL";

export const REVIEW_GET_ALL_REQUEST = "REVIEW_GET_ALL_REQUEST";
export const REVIEW_GET_ALL_SUCCESS = "REVIEW_GET_ALL_SUCCESS";
export const REVIEW_GET_ALL_FAIL = "REVIEW_GET_ALL_FAIL";

export const REVIEW_ADD_REVIEW_REQUEST = "REVIEW_ADD_REVIEW_REQUEST";
export const REVIEW_ADD_REVIEW_SUCCESS = "REVIEW_ADD_REVIEW_SUCCESS";
export const REVIEW_ADD_REVIEW_FAIL = "REVIEW_ADD_REVIEW_FAIL";

export const REVIEW_UPDATE_REVIEW_REQUEST = "REVIEW_UPDATE_REVIEW_REQUEST";
export const REVIEW_UPDATE_REVIEW_SUCCESS = "REVIEW_UPDATE_REVIEW_SUCCESS";
export const REVIEW_UPDATE_REVIEW_FAIL = "REVIEW_update_REVIEW_FAIL";

export const REVIEW_DELETE_REVIEW_REQUEST = "REVIEW_DELETE_REVIEW_REQUEST";
export const REVIEW_DELETE_REVIEW_SUCCESS = "REVIEW_DELETE_REVIEW_SUCCESS";
export const REVIEW_DELETE_REVIEW_FAIL = "REVIEW_DELETE_REVIEW_FAIL";
