export const REVIEW_ADD_REVIEWS_REQUEST = "REVIEW_ADD_REVIEWS_REQUEST";
export const REVIEW_ADD_REVIEWS_SUCCESS = "REVIEW_ADD_REVIEWS_SUCCESS";
export const REVIEW_ADD_REVIEWS_FAIL = "REVIEW_ADD_REVIEWS_FAIL";

export const REVIEW_GET_ALL_REQUEST = "REVIEW_GET_ALL_REQUEST";
export const REVIEW_GET_ALL_SUCCESS = "REVIEW_GET_ALL_SUCCESS";
export const REVIEW_GET_ALL_FAIL = "REVIEW_GET_ALL_FAIL";

export const REVIEW_ADD_REVIEW_REQUEST = "REVIEW_ADD_REVIEW_REQUEST";
export const REVIEW_ADD_REVIEW_SUCCESS = "REVIEW_ADD_REVIEW_SUCCESS";
export const REVIEW_ADD_REVIEW_FAIL = "REVIEW_ADD_REVIEW_FAIL";

export const REVIEW_UPDATE_REVIEW_REQUEST = "REVIEW_UPDATE_REVIEW_REQUEST";
export const REVIEW_UPDATE_REVIEW_SUCCESS = "REVIEW_UPDATE_REVIEW_SUCCESS";
export const REVIEW_UPDATE_REVIEW_FAIL = "REVIEW_update_REVIEW_FAIL";

export const REVIEW_DELETE_REVIEW_REQUEST = "REVIEW_DELETE_REVIEW_REQUEST";
export const REVIEW_DELETE_REVIEW_SUCCESS = "REVIEW_DELETE_REVIEW_SUCCESS";
export const REVIEW_DELETE_REVIEW_FAIL = "REVIEW_DELETE_REVIEW_FAIL";

export const REVIEW_ADD_REPORT_REQUEST = "REVIEW_ADD_REPORT_REQUEST";
export const REVIEW_ADD_REPORT_SUCCESS = "REVIEW_ADD_REPORT_SUCCESS";
export const REVIEW_ADD_REPORT_FAIL = "REVIEW_ADD_REPORT_FAIL";

export const REVIEW_GET_TOTAL_REVIEWS = "REVIEW_GET_TOTAL_REVIEWS";

export const REVIEW_HELPFUL_SUCCESS = "REVIEW_HELPFUL_SUCCESS";
export const REVIEW_HELPFUL_FAIL = "REVIEW_HELPFUL_FAIL";

export const REVIEW_GET_HELPFULNESS_REQUEST = "REVIEW_GET_HELPFULNESS_REQUEST";
export const REVIEW_GET_HELPFULNESS_SUCCESS = "REVIEW_GET_HELPFULNESS_SUCCESS";
export const REVIEW_GET_HELPFULNESS_FAIL = "REVIEW_GET_HELPFULNESS_FAIL";

export const REVIEW_DELETE_HELPFULNESS_REQUEST =
  "REVIEW_DELETE_HELPFULNESS_REQUEST";
export const REVIEW_DELETE_HELPFULNESS_SUCCESS =
  "REVIEW_DELETE_HELPFULNESS_SUCCESS";
export const REVIEW_DELETE_HELPFULNESS_FAIL = "REVIEW_DELETE_HELPFULNESS_FAIL";
