export const SUBMENU_OPEN = "SUBMENU_OPEN";
export const SUBMENU_CLOSE = "SUBMENU_CLOSE";
export const SUBMENU_CLOSE_ALL = "SUBMENU_CLOSE_ALL";

export const SUBMENU_SUB_OPEN = "SUBMENU_SUB_OPEN";
export const SUBMENU_SUB_CLOSE = "SUBMENU_SUB_CLOSE";
export const SUBMENU_SUB_CLOSE_ALL = "SUBMENU_SUB_CLOSE_ALL";
