export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_FIND_EMAIL_SUCCESS = "USER_FIND_EMAIL_SUCCESS";
export const USER_FIND_EMAIL_FAIL = "USER_FIND_EMAIL_FAIL";

export const USER_SIGN_IN_REQUEST = "USER_SIGN_IN_REQUEST";
export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS";
export const USER_SIGN_IN_FAIL = "USER_SIGN_IN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_FORGOT_PASSWORD = "USER_FORGOT_PASSWORD_REQUEST";
export const USER_FORGOT_PASSWORD_SUCCESS = "USER_FORGOT_PASSWORD_SUCCESS";
export const USER_FORGOT_PASSWORD_FAIL = "USER_FORGOT_PASSWORD_FAIL";
export const USER_FORGOT_PASSWORD_TIME_OUT = "USER_FORGOT_PASSWORD_TIME_OUT";
export const USER_FORGOT_PASSWORD_RESET = "USER_FORGOT_PASSWORD_RESET";
export const USER_FORGOT_PASSWORD_RESET_SUCCESS =
  "USER_FORGOT_PASSWORD_RESET_SUCCESS";
export const USER_FORGOT_PASSWORD_RESET_FAIL =
  "USER_FORGOT_PASSWORD_RESET_FAIL";

export const USER_FORGOT_PASSWORD_TOKEN_VALID =
  "USER_FORGOT_PASSWORD_TOKEN_VALID";

export const USER_FORGOT_PASSWORD_TOKEN_INVALID =
  "USER_FORGOT_PASSWORD_TOKEN_INVALID";
